//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Button module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button1;
        
        /// <summary>The Motor Driver L298 module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MotorDriverL298 motorDriverL298;
        
        /// <summary>The USB Client DP module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientDP usbClientDP;
        
        /// <summary>The USB Host module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBHost usbHost;
        
        /// <summary>The Multicolor LED module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLED leftLed;
        
        /// <summary>The Multicolor LED module using socket * of leftLed.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLED rightLed;
        
        /// <summary>The Button module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button2;
        
        /// <summary>The Display T35 module using sockets 14, 13, 12 and 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayT35 displayT35;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpider Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpider)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.button1 = new GTM.GHIElectronics.Button(4);
            this.motorDriverL298 = new GTM.GHIElectronics.MotorDriverL298(11);
            this.usbClientDP = new GTM.GHIElectronics.USBClientDP(1);
            this.usbHost = new GTM.GHIElectronics.USBHost(3);
            this.leftLed = new GTM.GHIElectronics.MulticolorLED(6);
            this.rightLed = new GTM.GHIElectronics.MulticolorLED(this.leftLed.DaisyLinkSocketNumber);
            this.button2 = new GTM.GHIElectronics.Button(9);
            this.displayT35 = new GTM.GHIElectronics.DisplayT35(14, 13, 12, 10);
        }
    }
}
